# Training config names
TRAIN_CFG_MISTRAL = "mistral"
TRAIN_CFG_LLAMA = "llama"
TRAIN_CFG_ARC = "arc"
TRAIN_CFG_ETHICS = "ethics"
TRAIN_CFG_MMLU = "mmlu"

# Defaults training config values
TRAIN_CFG_DEFAULT_MODEL = TRAIN_CFG_MISTRAL
TRAIN_CFG_DEFAULT_DATASET = TRAIN_CFG_ARC
TRAIN_CFG_DEFAULT_MAX_LEN = 1024
TRAIN_CFG_DEFAULT_NOISE = 0.0
TRAIN_CFG_DEFAULT_R = 8
TRAIN_CFG_DEFAULT_ALPHA = 16

# Dataset status
DATASET_BARE_LABEL = "bare"
DATASET_TRUE_LABEL = "true"
DATASET_RANDOM_LABEL = "random"
