# Training config names
TRAIN_CFG_MISTRAL = "mistral"
TRAIN_CFG_LLAMA = "llama"
TRAIN_CFG_DUMMY_LLAMA = "dummy_llama"
TRAIN_CFG_ARC = "arc"
TRAIN_CFG_ETHICS = "ethics"
TRAIN_CFG_MMLU = "mmlu"

# Defaults training config values
TRAIN_CFG_DEFAULT_MODEL = TRAIN_CFG_MISTRAL
TRAIN_CFG_DEFAULT_DATASET = TRAIN_CFG_ARC
TRAIN_CFG_DEFAULT_MAX_LEN = 1024
TRAIN_CFG_DEFAULT_LABEL_NOISE = 0.0
TRAIN_CFG_DEFAULT_data_seed = 0
TRAIN_CFG_DEFAULT_SPLIT_ID = 0
TRAIN_CFG_DEFAULT_SPLIT_PROP = 1.0
TRAIN_CFG_DEFAULT_LORA_R = 8
TRAIN_CFG_DEFAULT_LORA_ALPHA = 16
TRAIN_CFG_DEFAULT_LORA_DROPOUT = 0.05
TRAIN_CFG_DEFAULT_ACCELERATOR = "cpu"
TRAIN_CFG_DEFAULT_EPOCH_DONE = 0
TRAIN_CFG_DEFAULT_EPOCH_TOTAL = 1

# Dataset status
DATASET_BARE_LABEL = "bare"
DATASET_TRUE_LABEL = "true"
DATASET_RANDOM_LABEL = "random"
