repos:
-   repo: .cache/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: .cache/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: .cache/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort
        args: ["--profile", "black"]
-   repo: local
    hooks:
    -   id: run-tests
        name: Pytest tests
        entry: bash -c 'if [ "$(git symbolic-ref --short HEAD)" = "main" ]; then PYTHONPATH=. pytest; fi'
        language: system
        pass_filenames: false
        always_run: true
