repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort
        args: ["--profile", "black"]
-   repo: local
    hooks:
    -   id: run-tests
        name: Pytest tests
        entry: bash -c 'if [ "$(git symbolic-ref --short HEAD)" = "main" ]; then PYTHONPATH=. pytest; fi'
        language: system
        pass_filenames: false
        always_run: true
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets
        name: 'detect-secrets-non-jupyter'
        args: ['--baseline', '.secrets.baseline', "--base64-limit", "0.0", '--exclude-files', '.*\.ipynb$', ]
        exclude: package.lock.json
    -   id: detect-secrets
        name: 'detect-secrets-jupyter'
        args: ['--baseline', '.secrets.baseline', "--base64-limit", "0.0", '--exclude-files', '.*[^i][^p][^y][^n][^b]$', '--exclude-lines', '"(hash|id|image/\w+)":.*', ]
