name: LLM Grokking Tests

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install package dependencies
        run: pip install -r requirements.txt
      - name: Install development dependencies
        run: pip install -r .github/dev_requirements.txt
      - name: Show installed dependencies
        run: pip freeze
      - name: Run unit tests
        run: PYTHONPATH=./src python -m pytest
